### ISSUE TITLE
Need update for julia?

### ISSUE THREAD

**Issue by Shunsuke-Hori** [QuantEcon/QuantEcon.cheatsheet#52] opened 2018-08-08 19:34 UTC
I'm now trying julia 0.7 and I think there are many deprecations in the cheetsheet https://cheatsheets.quantecon.org/

(should we add version info?)

**Comment by jstac** [comment] 2018-08-09 03:14
According to @jlperla v1.0 is just around the corner, so maybe we should wait a week or two?

IEither way, any help updating the cheatsheet would be much appreciated.

**Comment by jlperla** [comment] 2018-08-09 03:20
This might be a good task for arnav, but let's wait a week or two. The issue is that the decoupled standard library components, etc make dependencies trickier than before, and we might need to figure out a good way to organize them

**Comment by jlperla** [comment] 2018-08-30 21:18
cc: @arnavs @Nosferican

One of the main Julia cheat-sheets is also being updated, https://github.com/JuliaDocs/Julia-Cheat-Sheet   so it may make sense to wait a week or two so that converges to see what can be borrowed.  That said, I think it is still worthwhile to have a QuantEcon one, which would have a curated list of things that economists typically use.

Just to add in a few notes I had from a first review.
- Fix the anonymous functions section (It currently doesn't mention Julias)
- Named tuples and anymous structures
- merging of anonymous structures with `merge...)
- Closures
- applying a function to a vector (i.e. broadcasting)
- applying a function to a vector with a fixed value (i.e. broadcasting where you need the `Ref`)
- applying a function to 2 vectors
-  inplace modification of a variable (i.e. when you need `.=` )
- inplace matrix multiplication
- sparse and tridiagonal matrices and banded matrices.
- eye to I
- preallocation of a vector of the same size as another
- linearly spaced values, ranges by integer

**Comment by arnavs** [comment] 2018-08-30 21:28
Thanks @jlperla. Let me know if/when you'd like me to start on this.

**Comment by jlperla** [comment] 2018-08-30 21:33
I think we should wait.  Partially to see what we end up using/removing from the lecture notes.  If we don't use a particular control structure or programming pattern at all, then we should consider whether it is necessary on the cheat sheet.

**Comment by jlperla** [comment] 2018-11-16 22:49
cc: @arnavs @Nosferican Just a ping on the cheat sheet.  I think we should update this for Julia and potentially add in some other material which comes up a lot.

Also, maybe https://juliadocs.github.io/Julia-Cheat-Sheet/ could be referenced?

We should try to keep things in line with our style guide wherever possible. A few particular points
- [ ] We need to say at the top what the implied `using` is.  I think `using Statistics, LinearAlgebra, Compat`  Maybe move the "In the Python code we assume..." to the top and add a similar one for Julia?  If they are at the bottom, people may miss them.
- [ ] `Linearly spaced vector of k points`
     * I think we should say `A = range(1, 5, stops=k) # with Compat or v1.1` so we can use the new notation
- [ ] `eye(2, 2)` should be `I` 
- [ ] I think that `diagm([1; 2; 3])` becomes `Diagonal([1; 2; 3])`
- [ ] For `dot(A, B)` make sure the dot operator as well.
- [ ] `sum(A, 1)` will need the keywords
- [ ] `for i = 1:N` should be `for i in 1:N`
- [ ] the `Function: one line/ anonymous` is missing the anonymous in julia.  I think these should be split up a little.  Anonymous is not just a one-line thing.  Maybe "Function: anonymous" which has all three anonymous functions, then "Function: multiple lines" is just "Function" and we can show the julia one line as an alternative?

New stuff to add, which we could hopefully find a python/matlab equivalent for
- [ ] Tuples.  Matlab should say N/A
- [ ] Named tuples/Anonymous structures.  Matlab has unnamed structures, not sure about python (which might use dicts?)
- [ ] Preallocating vector of similar type/size.  In matlab I think you are best going `zeros(size(x, 1), size(x, 2))` or something like that.
```
x = [1.0 2.0; 3.0 4.0]
y = similar(x)
```
- [ ] Closures.  Do the following in all three languages
```
a = 2.0
f(x) = a + x
f(1.0)
```
- [ ] Applying a function to a vector/broadcasting
```
f(x) = x^2
g(x, y) = x + 2 + y^2
x = 1:10
y = 2:11
f.(x)
g.(x,y) 
```
- [ ] Inplace matrix multiplication.  Not sure if matlab or python can do it, but comes up a lot.
```
x = [1, 2]
A = [1 2; 3 4]
y = similar(x)
mul!(y, A, x) # inplace version of y = A * x
```
- [ ] Inplace modification in a function (default in matlab, not sure about python)
```
function f!(out, x)
    out .= x.^2
end
```
- [ ] Sparse matrices
```
using SparseArrays 
A = spzeros(2, 2)
A(1, 2) = 4
A(3, 3)  = 1
```
matlab:
```
A = sparse(3, 3)
A(1, 2) = 4
A(3, 3) = 1
```
- [ ]  Tridiagonal matrices
```
Tridiagonal([1, 2, 3],  [7, 8, 9, 0], [4, 5, 6])
```
Matlab:
```
>> A = [1 7 NaN;
              2 8 4;
              3 9 5;
              NaN 0 6]
a = spdiags(A, [-1 0 1], 4, 4) # stored as sparse, not tridiagonal
```

**Comment by jlperla** [comment] 2018-11-16 22:50
I think we need to keep a jupyter notebook for python/julia and a matlab .m file to check all of the comparisons.

**Comment by arnavs** [comment] 2018-11-21 21:33
cc @ajozefiak. task is to implement in Python the new stuff for Julia

**Comment by arnavs** [comment] 2018-11-21 22:18
Also create/organize the Jupyter notebook as above.

**Comment by arnavs** [comment] 2019-01-08 00:21
Closing as this has been taken care of with the move to the Julia 1.0 lectures.

**Closed as completed by arnavs** 2019-01-08 00:21 UTC
